### ISSUE TITLE
mix ecto.migrate fails

### ISSUE THREAD

**Issue by brado** [michalmuskala/mongodb_ecto#61]
I previously posted in a closed issue (forgive me for that), so I'm posting a new one. I'm new to the Phoenix Framework and I'm trying to get it working with MongoDB. I have the following dependencies defined in my mix.exs:
```
  defp deps do
    [
      {:phoenix, "~> 1.1"},
      {:phoenix_ecto, "~> 2.0"},
      {:phoenix_html, "~> 2.3"},
      {:phoenix_live_reload, "~> 1.0", only: :dev},
      {:mongodb_ecto, github: "michalmuskala/mongodb_ecto"},
# NOTE: I tried this also, same result...   {:mongodb_ecto, "~> 0.1.2"},
      {:cowboy, "~> 1.0"},
      {:exrm, "~> 1.0.0-rc7"},
      {:gettext, "~> 0.9"}
    ]
  end
```
When I run
```
mix ecto.migrate
```
I receive the following error: 
```
$ mix ecto.migrate

16:10:37.296 [info]  Already up
** (UndefinedFunctionError) undefined function Mongo.Ecto.stop/3
    (mongodb_ecto) Mongo.Ecto.stop(MyApp.Repo, #PID<0.182.0>, 5000)
    (ecto) lib/mix/ecto.ex:94: Mix.Ecto.ensure_stopped/2
    (elixir) lib/enum.ex:604: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:604: Enum.each/2
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2
```
This is a complete blocker to me moving further with Phoenix / MongoDB. Does anyone know how to get past this error? 

Thanks a million in advance.

**Comment by brado** [comment]
I looked into the source code of mongo_ecto.ex, and the problem appears to be the form of the stop function, which takes only two parameters, while the current version of Ecto (v1.1.1) specifies stop/3:

From the Ecto v1.1.1 doc for Ecto.Adapter (http://hexdocs.pm/ecto/Ecto.Adapter.html):
**stop(repo, pid, timeout)**
*Shuts down the repository represented by the given pid*

I'm new to Ecto and I'm not sure exactly how to fix this, but essentially the repo parameter needs to be added to the present Mongo.Ecto module stop function, and the stop needs to occur for the specified repo. 

Any help is appreciated.

**Comment by michalmuskala** [comment]
It's a known issue of ecto 1.1
I'll be working on resolving it today.

**Comment by brado** [comment]
@michalmuskala thanks so much. I'm new to Elixir and Ecto, so if I had a good handle on what to do with the extra repository parameter I'd fix it up myself and get a pull request over to you. I'm not exactly sure how a stop is effected on a specific repository with respect to Ecto and MongoDB, but if I knew I'd try to help out. Perhaps when I get my sea legs on this stuff I can contribute if I run across an issue.

**Comment by brado** [comment]
@michalmuskala any status on this? Is there anything I can do to help fix this problem?

**Comment by michalmuskala** [comment]
Hey. I looked into this, and even though this exact issue is a two line change to fix, unfortunately there are more issues with Ecto 1.1 that are harder to overcome.

As much as it pains me, as a quick solution, I must recommend downgrading to Ecto 1.0 for the time being.

**Comment by brado** [comment]
Ok...could you direct me to exactly how to downgrade Ecto to 1.0? Ecto isn't referenced directly per se in project dependencies, but rather phoenix_ecto as in: 
```
      {:phoenix_ecto, "~> 2.0"},
```
That version is dictated by the Phoenix Framework upgrade from 1.0.x to 1.1.0, (which has bigger implications than just Ecto) so I really hope there is a way to downgrade Ecto without affecting the phoenix_ecto version, because having to downgrade the Phoenix Framework in its entirety is going to have wider ramifications. I'm not sure how to downgrade Ecto....can you tell me how to do so? 

Thanks....

**Comment by brado** [comment]
Based on some other references I found, I am trying this in my Phoenix Framework project's mix.exs: 
```
    {:ecto, "~> 1.0", override: true}
```
But this still isn't working. After a mix deps.clean --all, a mix deps.get shows this: 
```
* Getting ecto (Hex package)
Checking package (https://s3.amazonaws.com/s3.hex.pm/tarballs/ecto-1.1.1.tar)
...
lib/mongo_ecto.ex:1: warning: undefined behaviour function stop/3 (for behaviour Ecto.Adapter)
```
I'm not sure how to get around this, but I have to soon or else I'm going to have to punt the entire Phoenix Framework, as I need my web app talking to MongoDB. Any help is greatly appreciated. Thx.

**Comment by tomjoro** [comment]
(trying to help)... Seems radical to downgrade Ecto simply because migrations with MongoDB don't work... since they really don't do much anyways.

In MongoDB you don't need to create tables, just start inserting.  And if you need an index just create one using the mongo console: db.collection.ensureIndex( { a: 1 }, { unique: true } )..   

This way you can continue your project without spending time going backwards (and soon forwards again) in versions. Btw - i'm using same versions as you, and just use it without the migrations.

**Comment by michalmuskala** [comment]
Unfortunately it's not just migrations, there are more things that are broken between `mongo_ecto` and Ecto 1.1.

`~> 1.0` will still match 1.1, you need to exclude it with something like `~> 1.0.0`.

**Comment by brado** [comment]
It would appear I've been able to get beyond the problem, for now, but I still ran into a few problems finding exactly what needed to be downgraded. First, in my mix.exs I tried leaving phoenix_ecto at 2.0 and using an override of ecto 1.0.7, as such: 
```
      {:ecto, "~> 1.0.7", override: true},
      {:phoenix_ecto, "~> 2.0"},
```
Unfortunately, this blew up as soon as I attempted an operation (such as a delete or new) which required the Eco.primary_key/1 function: 
```
Request: GET /mydocument/new
** (exit) an exception was raised:
    ** (UndefinedFunctionError) undefined function Ecto.primary_key/1
```
So then in my mix.exs I removed the Ecto override and changed phoenix_ecto back to its most recent 1.x version (1.2.0), as such: 
```
      {:phoenix_ecto, "~> 1.2.0"},
```
That version of phoenix_ecto pulls in ecto 1.0.7 without need for specifying it explicitly, and seems to work fine with all CRUD operations. 

Any idea when mongodb_ecto will support ecto 1.1.1, thus allowing phoenix_ecto 2.0?

**Comment by michalmuskala** [comment]
I would love to fix those issues, but unfortunately I'm currently in my exam period, and I don't have enough time to tackle this. I can't give any better estimate than "as soon as I can" right now.

**Comment by tomjoro** [comment]
anyway I could i help out - implement some of this stuff?

**Comment by brado** [comment]
It turns out that this is a bigger issue than I originally thought. As I need Ecto embeds, I was following this blog post by Jose Valim on how to accomplish this: 

http://blog.plataformatec.com.br/2015/08/working-with-ecto-associations-and-embeds/

From the post, the rub: 

>Note: you will need phoenix_ecto 2.0 in order to follow this example.

As I mentioned above, I had to drop down from phoenix_ecto 2.0 to 1.2.0 because 2.0 depends on ecto 1.1.1, and won't compile with mongo_ecto. But phoenix_ecto 1.2.0 requires ecto 1.0.7, and this appears to cause these compile problems with the embeds listed in the blog post: 
```
== Compilation error on file web/models/todo_list.ex ==
** (CompileError) web/models/todo_list.ex:23: undefined function cast_assoc/3
    (stdlib) lists.erl:1337: :lists.foreach/2
    (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:100: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8
```
I'm now stuck. I need mongo_ecto but I need to have embedded models with mongodb. I'm not sure how to fix this, but my best guess is one of two routes:

1. Is there any way to get phoenix_ecto 2.0 working with a pre-ecto 1.1.1 version? 
2. Is there a syntactical change to the code / technique used in that blog post which will successfully facilitate embeds with phoenix_ecto 1.2.0 and ecto 1.0.7? 

Help would be greatly appreciated. Thx.

**Comment by michalmuskala** [comment]
The previous version of the article you're mentioning was directed at Ecto 1.0. Maybe there's access to the old version somewhere.

The main difference is that instead of separate function `cast_assoc` and `cast_embed` you added the fields directly to the required or optional list in `cast/4`.

\cc @josevalim is the old associations article accessible somewhere?

**Comment by brado** [comment]
@michalmuskala @josevalim This actually raises an interesting question...the blog post referenced above mentions use on MongoDB, and requires phoenix_ecto 2.0 -- so how was this achieved with mongo_ecto -- what versions of dependencies were used to accomplish this and compile / run cleanly? 

I have not been able to find a way to use phoenix_ecto 2.0 with any version of mongo_ecto and compile / run cleanly. I am using the mongo_ecto master because I had the same error that was resolved on the master in Issue #56.

So I am assuming that given the blog post is discussing embeds in MongoDB and requires phoenix_ecto 2.0, and I'm also assuming it was using the mongodb_ecto library, can someone list the dependencies which I should include in my mix.exs to get this to work with phoenix_ecto 2.0?

**Comment by michalmuskala** [comment]
There is no version of `mongo_ecto` right now that works with Ecto 1.1 or `phoenix_ecto` 2.0 (those are the same constraint as `phoenix_ecto` 2.0 requires Ecto 1.1).

What happened in the article, I suspect, is that the article was initially composed for Ecto 1.0 where `mongo_ecto` worked fine. Since then it was updated for Ecto 1.1, but the references to MongoDB were left.

**Comment by josevalim** [comment]
Yes, I will remove the references to mongo. I think MongoEcto should target Ecto 2.0 which should be out in a ~month.

**Comment by brado** [comment]
Thanks guys....please make it know with some kind of public splash, and/or post a response to this issue as soon as mongo_ecto is compatible with phoenix_ecto 2.0. That will be a good day. A couple of parting points for now: 

1. @josevalim -- first, thanks for all of your work on Elixir/Phoenix. I'm loving both right now, and look forward to being able to contribute when an issue arises where I can, and my mastery of the domain is sufficient. 

In the meantime, I highly encourage you **not** to remove the references to MongoDB in the article. When working with MongoDB, embedding documents is fundamental schema design 101, and you cannot get very far without knowing how to do that. Your article was all I found which spoke to this. In fact, I'd highly recommend (and perhaps I'll contribute at some point in the future) articles which specifically discuss use with MongoDB, because there are some key differences from relational SQL databases which aren't necessarily obvious: 

- Storage effects in MongoDB when using has_many vs embeds_many.
- Schema creation and migrating changesets (MongoDB works on the fly vs. static).
- timestamps. 
- etc.

Instead of removing references to MongoDB, which will remove a helpful reference for those doing the same as I....using Phoenix and MongoDB -- just include notes which say the following: 

- You must use phoenix_ecto 1.2.0, ecto 1.0.7, and mongodb_ecto trunk from github.
- as @michalmuskala said, in todo_list.ex, the recommended cast_assoc needs to be commented out in favor of adding todo_items to the required_fields list. 

I got this article to work with that combination. 

2. In going through this exercise of trying to get a parent-child hierarchy created in MongoDB with associated Phoenix models and action HTML pages, one area of definite phoenix improvement became obvious: handling of parent-child relationships both in UI, and with respect to cascading deletion when the parent is deleted. 

The UI with respect to the todo_items children is a little kludgy, and even more so with respect to deletion -- if you delete the list (as opposed to individual items) the children get orphaned in MongoDB. What would be superior is a proper child table-type arrangement which make management of the child list a little more robust. It would be really neat if we could add that somehow to the generators so that developers could get that very well-worn pattern mostly handled out of the box. 

@michalmuskala please forgive me for the extra discussion here -- I know that discussion of this blog post is technically a bit downstream from mongo-ecto itself, but it is a valid use-case which gives context to mongo_ecto's pragmatic use and compatibility. I thank everyone for their contributions to the conversation, as it has allowed me to struggle towards something that at least is working, and it appears for the moment that I can continue to move forward with. 

I'll look forward to seeing the ecto 2.0 and mongo_ecto updates coming soon! Thanks again.

**Comment by matiasinsaurralde** [comment]
I'm getting the same problem :(

**Comment by michalmuskala** [comment]
@matiasinsaurralde what versions of `Ecto` and `Mongo.Ecto` are you using?

**Comment by blacksails** [comment]
@michalmuskala have you decided to target ecto 2, for a next release? 
If so, have you gotten an overview about what needs to be changed in the mongodb_ecto project for it to be compatible with ecto 2.0? If there is much work to do, I would be happy to be of assistance.

**Comment by michalmuskala** [comment]
@blacksails yes, I plan next release to be compatible with Ecto 2.0. I'm not yet exactly sure what is needed in order to support it. I'll try to create some tasks for 2.0 support, and you'll be very welcome to take one of them.

The thing is there are major changes planned for the driver, but time-frame there is not clear. I think we'll probably stick with the current version for now.

**Comment by brado** [comment]
Is there any status of a release to be compatible with Ecto 2.0, or at least one compatible with phoenix_ecto 2.0? What is the newest version of both Ecto and phoenix_ecto that can be used with mongodb_ecto? Is there any ETA for when mongodb_ecto will catch up with and support ecto and phoenix_ecto? 

Thanks....

**Comment by michalmuskala** [comment]
Unfortunately the status hasn't changed much lately. I would love to speed this up and deliver an updated version, but I simply don't have time to do this right now.
I will try to create a timeline over the weekend and some tasks, so if someone is up for it, they can try to help.

When porting, I will update straight to `ecto` 2.0 (`phoenix_ecto` 3.0) since it's much easier task to do that. Ecto 1.1 has several incompatibilities in the adapter layer that are quite hard to circumvent.

**Comment by dhonig** [comment]
:+1:  Did you ever get a chance to update the task list?

**Comment by michalmuskala** [comment]
There are some tasks listed in https://github.com/michalmuskala/mongodb_ecto/pull/84 hopefully I'll get the system to the state where the work can be parallelized and shared.

**Comment by dhonig** [comment]
ok.  We are up to pitching in.  Thanks for the pointer.
